version: '3'
services:
  sqlite_single:
    container_name: sqlite_single
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data:/root/db
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
networks:
  traefik:
    external:
      name: traefik
  adminer:
    driver: bridge

