version: '3'
services:
  sqlite-single:
    container_name: sqlite-single
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data:/root/db
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
networks:
  adminer:
    external:
      name: adminer
