version: '3'
services:
  mariadb-single:
    container_name: mariadb-single
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - mariadb.env
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
networks:
  adminer:
    external:
      name: adminer
