version: '3'
services:
  arangodb-single:
    container_name: arangodb-single
    image: arangodb/arangodb:latest
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
    ports:
      - "8529:8529"
    volumes:
      - "./data:/var/lib/arangodb3"
      - "./apps:/var/lib/arangodb3-apps"
    env_file:
      - arangodb.env
networks:
  adminer:
    external:
      name: adminer
