version: '3'
services:
  mysql-single:
    container_name: mysql-single
    image: mysql:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
    volumes:
      - "./data:/var/lib/mysql"
    env_file:
      - mysql.env
networks:
  adminer:
    external:
      name: adminer
