version: '3.5'
services:
  adminer:
    image: adminer:latest
    container_name: "adminer"
    restart: unless-stopped
    ports:
      - "8014:8080"
    labels:
      - "traefik.frontend.rule=Host:adminer.lab.test"
      - "traefik.frontend.headers.STSSeconds=31536000"
      - "traefik.docker.network=traefik"
    networks:
      - adminer
      - traefik
    env_file:
      - adminer.env
networks:
  traefik:
    external:
      name: traefik
  adminer:
    name: adminer
    driver: bridge
