version: '3'
services:
  ravendb-single:
    container_name: ravendb-single
    image: ravendb/ravendb:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
    ports:
      - "8081:8080"
    volumes:
      - "./data:/opt/RavenDB/Server/RavenData"
      - "./config:/opt/RavenDB/config"
    env_file:
      - ravendb.env
networks:
  adminer:
    external:
      name: adminer
