version: '3'
services:
  postgresql-single:
    image: postgres:latest
    container_name: postgresql-single
    env_file:
      - postgresql.env
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - adminer
    restart: unless-stopped
networks:
  adminer:
    external:
      name: adminer
